apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rail-ticketing
type: Opaque
stringData:
  postgres-password: postgres
  schedule-password: schedule_pw
  inventory-password: inventory_pw
  booking-password: booking_pw
  quota-password: quota_pw
