spring:
  application:
    name: fare-service

  threads:
    virtual:
      enabled: true

  mvc:
    problemdetails:
      enabled: true

server:
  port: ${SERVER_PORT:8087}
  error:
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4318}/v1/traces
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4318}/v1/traces

clients:
  schedule:
    base-url: ${SCHEDULE_URL:http://localhost:8081}
    connect-timeout-ms: 500
    read-timeout-ms: 2000

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [${spring.application.name},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
